In [1]:
import pandas as pd

In [1]:
import pandas as pd
lowPotentialHubDF = pd.read_csv('Silver/Low_Potential_Hubs.csv')
monthlyVolunmDF = pd.read_csv('Silver/transactions_history_final_by_clean_totalSum_monthly.csv')

In [2]:
lowPotentialHubDF.head(10)

   Outlet_ID
0  OUT_00001
1  OUT_00002
2  OUT_00003
3  OUT_00004
4  OUT_00005
5  OUT_00006
6  OUT_00007
7  OUT_00008
8  OUT_00009
9  OUT_00011

In [3]:
monthlyVolunmDF.head(10)

   Outlet_ID year_month  Volume_Liters_Sum
0  OUT_00001    2023-03        1390.918670
1  OUT_00001    2023-06         382.687950
2  OUT_00001    2023-08         552.713934
3  OUT_00001    2023-10         541.861465
4  OUT_00001    2023-11         223.594015
5  OUT_00001    2024-03        1941.470001
6  OUT_00001    2024-05         350.532111
7  OUT_00001    2024-06         401.544922
8  OUT_00001    2024-07         248.414012
9  OUT_00001    2024-08         321.337314

In [4]:
redultDF = monthlyVolunmDF[monthlyVolunmDF['Outlet_ID'].isin(lowPotentialHubDF['Outlet_ID'])]

In [5]:
redultDF['year_month'] = pd.to_datetime(redultDF['year_month'], format='%Y-%m')
redultDF = redultDF.sort_values(by=['Outlet_ID', 'year_month']).reset_index(drop=True)
redultDF['year_month'] = redultDF['year_month'].dt.strftime('%Y-%m')

In [6]:
import pandas as pd
mediumPotentialHubDF = pd.read_csv('Silver/Medium_Potential_Hubs.csv')
highPotentialHubDF = pd.read_csv('Silver/High_Potential_Hubs.csv')
elitePotentialHubDF = pd.read_csv('Silver/Elite_Potential_Hub.csv')

In [ ]:
redultDF2 = monthlyVolunmDF[monthlyVolunmDF['Outlet_ID'].isin(mediumPotentialHubDF['Outlet_ID'])]
redultDF3 = monthlyVolunmDF[monthlyVolunmDF['Outlet_ID'].isin(highPotentialHubDF['Outlet_ID'])]
redultDF4 = monthlyVolunmDF[monthlyVolunmDF['Outlet_ID'].isin(elitePotentialHubDF['Outlet_ID'])]

In [10]:
redultDF2['year_month'] = pd.to_datetime(redultDF2['year_month'], format='%Y-%m')
redultDF2 = redultDF2.sort_values(by=['Outlet_ID', 'year_month']).reset_index(drop=True)
redultDF2['year_month'] = redultDF2['year_month'].dt.strftime('%Y-%m')

In [11]:
redultDF3['year_month'] = pd.to_datetime(redultDF3['year_month'], format='%Y-%m')
redultDF3 = redultDF3.sort_values(by=['Outlet_ID', 'year_month']).reset_index(drop=True)
redultDF3['year_month'] = redultDF3['year_month'].dt.strftime('%Y-%m')

In [12]:
redultDF4['year_month'] = pd.to_datetime(redultDF4['year_month'], format='%Y-%m')
redultDF4 = redultDF4.sort_values(by=['Outlet_ID', 'year_month']).reset_index(drop=True)
redultDF4['year_month'] = redultDF4['year_month'].dt.strftime('%Y-%m')

In [21]:
holidaySortDF = pd.read_csv('Silver/holiday_list_by_clean.csv')
outletDetailDF = pd.read_csv('Bronze/outlet_master.csv')
transactionWithDistributorDF = pd.read_csv('Silver/transactions_history_final_by_clean.csv')
distributorSeasonDF = pd.read_csv('Silver/distributor_seasonality_details_by_clean.csv')

In [22]:

redultDF1_2 = redultDF.merge(holidaySortDF, on='year_month', how='left')
resultDF2_2 = redultDF2.merge(holidaySortDF, on='year_month', how='left')
resultDF3_2 = redultDF3.merge(holidaySortDF, on='year_month', how='left')
resultDF4_2 = redultDF4.merge(holidaySortDF, on='year_month', how='left')

In [23]:
redultDF1_2 = redultDF1_2.merge(outletDetailDF, on='Outlet_ID', how='left')
resultDF2_2 = resultDF2_2.merge(outletDetailDF, on='Outlet_ID', how='left')
resultDF3_2 = resultDF3_2.merge(outletDetailDF, on='Outlet_ID', how='left')
resultDF4_2 = resultDF4_2.merge(outletDetailDF, on='Outlet_ID', how='left')

In [ ]:
# redultDF1_2 = redultDF1_2.merge(transactionWithDistributorDF[['Outlet_ID','Distributor_ID']], on='Outlet_ID', how='left')
# resultDF2_2 = resultDF2_2.merge(transactionWithDistributorDF[['Outlet_ID','Distributor_ID']], on='Outlet_ID', how='left')
# resultDF3_2 = resultDF3_2.merge(transactionWithDistributorDF[['Outlet_ID','Distributor_ID']], on='Outlet_ID', how='left')
# resultDF4_2 = resultDF4_2.merge(transactionWithDistributorDF[['Outlet_ID','Distributor_ID']], on='Outlet_ID', how='left')

In [24]:
redultDF1_2.head(100)

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type
0,OUT_00001,2023-03,1390.918670,1,Medium,1,Grocry
1,OUT_00001,2023-06,382.687950,1,Medium,1,Grocry
2,OUT_00001,2023-08,552.713934,2,Medium,1,Grocry
3,OUT_00001,2023-10,541.861465,1,Medium,1,Grocry
4,OUT_00001,2023-11,223.594015,1,Medium,1,Grocry
...,...,...,...,...,...,...,...
95,OUT_00004,2025-04,477.128565,5,Medium,2,Pharmacy
96,OUT_00004,2025-05,394.574321,3,Medium,2,Pharmacy
97,OUT_00004,2025-06,437.133556,1,Medium,2,Pharmacy
98,OUT_00004,2025-07,677.418625,1,Medium,2,Pharmacy
99,OUT_00004,2025-08,658.027777,1,Medium,2,Pharmacy

In [25]:
len(redultDF1_2)

369387

In [26]:
resultDF2_2.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type
0,OUT_00013,2023-02,263.862501,3,Small,0,Hotel
1,OUT_00013,2023-03,602.049872,1,Small,0,Hotel
2,OUT_00013,2023-05,417.721471,4,Small,0,Hotel
3,OUT_00013,2023-06,374.356561,1,Small,0,Hotel
4,OUT_00013,2023-07,338.380509,1,Small,0,Hotel

In [27]:
resultDF3_2.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type
0,OUT_00040,2023-03,1398.296590,1,Large,4,SMMT
1,OUT_00040,2023-04,401.468891,4,Large,4,SMMT
2,OUT_00040,2023-05,180.347877,4,Large,4,SMMT
3,OUT_00040,2023-06,388.653100,1,Large,4,SMMT
4,OUT_00040,2023-07,131.595306,1,Large,4,SMMT

In [28]:
resultDF4_2.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type
0,OUT_00010,2023-03,844.561347,1,Small,0,Eatery
1,OUT_00010,2023-04,215.881831,4,Small,0,Eatery
2,OUT_00010,2023-05,417.348298,4,Small,0,Eatery
3,OUT_00010,2023-06,337.655756,1,Small,0,Eatery
4,OUT_00010,2023-07,263.052351,1,Small,0,Eatery

In [31]:
redultDF1_2.to_csv(r'Gold/Low_Potential_Hubs_Monthly_Volume.csv', index=False)
resultDF2_2.to_csv(r'Gold/Medium_Potential_Hubs_Monthly_Volume.csv', index=False)
resultDF3_2.to_csv(r'Gold/High_Potential_Hubs_Monthly_Volume.csv', index=False)
resultDF4_2.to_csv(r'Gold/Elite_Potential_Hubs_Monthly_Volume.csv', index=False)

In [30]:
total = len(redultDF1_2)+len(resultDF2_2)+len(resultDF3_2)+len(resultDF4_2)
total

445217

In [ ]:
df1 = pd.read_csv('Gold/Low_Potential_Hubs_Monthly_Volume.csv')
df2 = pd.read_csv('Gold/Medium_Potential_Hubs_Monthly_Volume.csv')
df3 = pd.read_csv('Gold/High_Potential_Hubs_Monthly_Volume.csv')
df4 = pd.read_csv('Gold/Elite_Potential_Hubs_Monthly_Volume.csv')

In [ ]:
redultDF1_2 = df1.merge(distributorSeasonDF[['Distributor_ID','Seasonality_Index']], on='Distributor_ID', how='left')
resultDF2_2 = df2.merge(distributorSeasonDF[['Distributor_ID','Seasonality_Index']], on='Distributor_ID', how='left')
resultDF3_2 = df3.merge(distributorSeasonDF[['Distributor_ID','Seasonality_Index']], on='Distributor_ID', how='left')
resultDF4_2 = df4.merge(distributorSeasonDF[['Distributor_ID','Seasonality_Index']], on='Distributor_ID', how='left')

In [ ]:
redultDF1_2.head()

In [ ]:
resultDF2_2.head()

In [ ]:
resultDF3_2.head()

In [ ]:
resultDF4_2.head()