In [8]:
import pandas as pd

In [9]:
elite_df = pd.read_csv('Elite_Predictions_2026_01.csv')
high_df    = pd.read_csv('High_Predictions_2026_01.csv')
medium_df  = pd.read_csv('Medium_Predictions_2026_01.csv')
low_df     = pd.read_csv('Low_Predictions_2026_01.csv')

In [10]:
elite_df.head()

   Outlet_ID  Predicted_Volume_Liters_2026_01
0  OUT_00010                       716.117419
1  OUT_00026                       934.669215
2  OUT_00246                       818.430891
3  OUT_00262                       791.620252
4  OUT_00303                       883.526977

In [11]:
high_df.head()

   Outlet_ID  Predicted_Volume_Liters_2026_01
0  OUT_00040                       814.019232
1  OUT_00044                       856.647006
2  OUT_00074                       740.842820
3  OUT_00078                       779.145023
4  OUT_00094                       603.633595

In [12]:
medium_df.head()

   Outlet_ID  Predicted_Volume_Liters_2026_01
0  OUT_00013                       717.160602
1  OUT_00014                       729.834317
2  OUT_00029                       703.510835
3  OUT_00032                       873.732969
4  OUT_00045                      1001.340312

In [13]:
low_df.head()

   Outlet_ID  Predicted_Volume_Liters_2026_01
0  OUT_00001                       955.616385
1  OUT_00002                      1021.410686
2  OUT_00003                       818.205805
3  OUT_00004                      1083.175519
4  OUT_00005                       990.209708

In [14]:
combined_df = pd.concat([elite_df, high_df, medium_df, low_df], ignore_index=True)

# Sort by Outlet_ID ascending
combined_df = combined_df.sort_values('Outlet_ID').reset_index(drop=True)

# Save
combined_df.to_csv('All_Predictions_2026_01.csv', index=False)