In [15]:
import pandas as pd

In [24]:
import pandas as pd
outlet_dist_df  = pd.read_csv('Silver/outlet_distributor.csv')
seasonality_df   = pd.read_csv('Silver/distributor_seasonality_details_by_clean.csv')
elite_df  = pd.read_csv('Gold/Elite_Potential_Hubs_Monthly_Volume.csv')
high_df  = pd.read_csv('Gold/High_Potential_Hubs_Monthly_Volume.csv')
low_df  = pd.read_csv('Gold/Low_Potential_Hubs_Monthly_Volume.csv')
medium_df  = pd.read_csv('Gold/Medium_Potential_Hubs_Monthly_Volume.csv')

In [25]:
outlet_dist_df.head()

   Outlet_ID Distributor_ID
0  OUT_00001      DIST_W_03
1  OUT_00002      DIST_W_02
2  OUT_00003      DIST_W_02
3  OUT_00004      DIST_W_01
4  OUT_00005      DIST_W_03

In [26]:
seasonality_df.head()

  year_month Distributor_ID Seasonality_Index
0    2023-01      DIST_W_01          Moderate
1    2023-01     DIST_NW_01          Moderate
2    2023-01      DIST_C_03          Moderate
3    2023-01      DIST_S_01         Favorable
4    2023-01      DIST_C_02          Moderate

In [28]:
elite_df.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type
0,OUT_00010,2023-03,844.561347,1,Small,0,Eatery
1,OUT_00010,2023-04,215.881831,4,Small,0,Eatery
2,OUT_00010,2023-05,417.348298,4,Small,0,Eatery
3,OUT_00010,2023-06,337.655756,1,Small,0,Eatery
4,OUT_00010,2023-07,263.052351,1,Small,0,Eatery

In [29]:
elite_df = elite_df.merge(outlet_dist_df, on='Outlet_ID', how='left')
high_df = high_df.merge(outlet_dist_df, on='Outlet_ID', how='left')
medium_df = medium_df.merge(outlet_dist_df, on='Outlet_ID', how='left')
low_df = low_df.merge(outlet_dist_df, on='Outlet_ID', how='left')

In [30]:
elite_df = elite_df.merge(seasonality_df, on=['Distributor_ID', 'year_month'], how='left')
high_df = high_df.merge(seasonality_df, on=['Distributor_ID', 'year_month'], how='left')
medium_df = medium_df.merge(seasonality_df, on=['Distributor_ID', 'year_month'], how='left')
low_df = low_df.merge(seasonality_df, on=['Distributor_ID', 'year_month'], how='left')

In [31]:
elite_df.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type,Distributor_ID,Seasonality_Index
0,OUT_00010,2023-03,844.561347,1,Small,0,Eatery,DIST_W_01,Moderate
1,OUT_00010,2023-04,215.881831,4,Small,0,Eatery,DIST_W_01,Favorable
2,OUT_00010,2023-05,417.348298,4,Small,0,Eatery,DIST_W_01,Un-Favorable
3,OUT_00010,2023-06,337.655756,1,Small,0,Eatery,DIST_W_01,Un-Favorable
4,OUT_00010,2023-07,263.052351,1,Small,0,Eatery,DIST_W_01,Moderate

In [32]:
high_df.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type,Distributor_ID,Seasonality_Index
0,OUT_00040,2023-03,1398.296590,1,Large,4,SMMT,DIST_W_01,Moderate
1,OUT_00040,2023-04,401.468891,4,Large,4,SMMT,DIST_W_01,Favorable
2,OUT_00040,2023-05,180.347877,4,Large,4,SMMT,DIST_W_01,Un-Favorable
3,OUT_00040,2023-06,388.653100,1,Large,4,SMMT,DIST_W_01,Un-Favorable
4,OUT_00040,2023-07,131.595306,1,Large,4,SMMT,DIST_W_01,Moderate

In [33]:
medium_df.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type,Distributor_ID,Seasonality_Index
0,OUT_00013,2023-02,263.862501,3,Small,0,Hotel,DIST_W_01,Moderate
1,OUT_00013,2023-03,602.049872,1,Small,0,Hotel,DIST_W_01,Moderate
2,OUT_00013,2023-05,417.721471,4,Small,0,Hotel,DIST_W_01,Un-Favorable
3,OUT_00013,2023-06,374.356561,1,Small,0,Hotel,DIST_W_01,Un-Favorable
4,OUT_00013,2023-07,338.380509,1,Small,0,Hotel,DIST_W_01,Moderate

In [34]:
low_df.head()

,Outlet_ID,year_month,Volume_Liters_Sum,monthly_holiday_count,Outlet_Size,Cooler_Count,Outlet_Type,Distributor_ID,Seasonality_Index
0,OUT_00001,2023-03,1390.918670,1,Medium,1,Grocry,DIST_W_03,Moderate
1,OUT_00001,2023-06,382.687950,1,Medium,1,Grocry,DIST_W_03,Un-Favorable
2,OUT_00001,2023-08,552.713934,2,Medium,1,Grocry,DIST_W_03,Moderate
3,OUT_00001,2023-10,541.861465,1,Medium,1,Grocry,DIST_W_03,Moderate
4,OUT_00001,2023-11,223.594015,1,Medium,1,Grocry,DIST_W_03,Moderate

In [35]:
elite_df.to_csv(r'Gold/Elite_Potential_Hubs_Monthly_Volume_2.csv',index=False)
high_df.to_csv(r'Gold/High_Potential_Hubs_Monthly_Volume_2.csv',index=False)
medium_df.to_csv(r'Gold/Medium_Potential_Hubs_Monthly_Volume_2.csv',index=False)
low_df.to_csv(r'Gold/Low_Potential_Hubs_Monthly_Volume_2.csv',index=False)

In [20]:
df1 = pd.read_csv('Gold/Low_Potential_Hubs_Monthly_Volume.csv')
df2 = pd.read_csv('Gold/Medium_Potential_Hubs_Monthly_Volume.csv')
df3 = pd.read_csv('Gold/High_Potential_Hubs_Monthly_Volume.csv')
df4 = pd.read_csv('Gold/Elite_Potential_Hubs_Monthly_Volume.csv')